import { jsPDF } from "jspdf";

export interface ReportPdfData {
  patient: {
    name?: string | null;
    patientId?: string | null;
    dateOfBirth?: Date | string | null;
    gender?: string | null;
  } | null;
  study: {
    studyId?: string | null;
    description?: string | null;
    modality?: string | null;
    bodyPart?: string | null;
    studyDate?: Date | string | null;
  } | null;
  report: {
    status: string;
    findings: string;
    impression: string;
    recommendations?: string | null;
    createdAt: Date | string;
  };
  radiologistName?: string | null;
}

export function exportReportPdf(data: ReportPdfData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = 210;
  const pageH = 297;
  const marginL = 20;
  const marginR = 20;
  const contentW = pageW - marginL - marginR;
  const footerReserve = 20; // mm reserved at bottom for footer
  const lineH = 5;
  let y = 20;
  const generatedAt = new Date().toLocaleString();

  // ── Footer (drawn on every page) ─────────────────────────────────────────
  const drawFooter = () => {
    doc.setDrawColor(180);
    doc.line(marginL, pageH - 15, pageW - marginR, pageH - 15);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by PACS Viewer", marginL, pageH - 9);
    doc.text(generatedAt, pageW - marginR, pageH - 9, { align: "right" });
  };

  // ── Page break guard ──────────────────────────────────────────────────────
  // Call before rendering any block that needs `neededH` mm of vertical space.
  const ensureSpace = (neededH: number) => {
    if (y + neededH > pageH - footerReserve) {
      drawFooter();
      doc.addPage();
      // Slim continuation header
      doc.setFillColor(30, 58, 138);
      doc.rect(0, 0, pageW, 10, "F");
      doc.setFontSize(9);
      doc.setTextColor(255);
      doc.setFont("helvetica", "bold");
      doc.text("PACS Viewer — Radiology Report (continued)", marginL, 7);
      // Restore body text state so subsequent text renders correctly
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(30);
      y = 18;
    }
  };

  // ── Render wrapped text that may span pages ───────────────────────────────
  const textBlock = (lines: string[]) => {
    for (const l of lines) {
      ensureSpace(lineH);
      doc.text(l, marginL, y);
      y += lineH;
    }
  };

  // ── Horizontal rule ───────────────────────────────────────────────────────
  const rule = () => {
    ensureSpace(6);
    doc.setDrawColor(180);
    doc.line(marginL, y, pageW - marginR, y);
    y += 5;
  };

  // ── Section heading + wrapped body ───────────────────────────────────────
  const section = (heading: string, body: string) => {
    ensureSpace(10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30);
    doc.text(heading, marginL, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(body || "N/A", contentW);
    textBlock(lines);
    y += 4;
  };

  // ─────────────────────────────────────────────────────────────────────────
  // PAGE 1 — Header
  // ─────────────────────────────────────────────────────────────────────────
  doc.setFillColor(30, 58, 138);
  doc.rect(0, 0, pageW, 18, "F");
  doc.setFontSize(13);
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.text("PACS Viewer — Radiology Report", marginL, 12);
  doc.setFontSize(8);
  doc.setTextColor(200, 220, 255);
  doc.text(data.report.status.toUpperCase(), pageW - marginR, 12, { align: "right" });

  y = 28;
  doc.setFont("helvetica", "normal");

  // Patient & Study info — two-column grid
  const col2X = marginL + contentW / 2 + 5;

  const patientFields: [string, string][] = [
    ["Patient Name", data.patient?.name || "N/A"],
    ["Patient ID",   data.patient?.patientId || "N/A"],
    ["Date of Birth", data.patient?.dateOfBirth ? new Date(data.patient.dateOfBirth).toLocaleDateString() : "N/A"],
    ["Gender",        data.patient?.gender ? (data.patient.gender.charAt(0).toUpperCase() + data.patient.gender.slice(1)) : "N/A"],
  ];
  const studyFields: [string, string][] = [
    ["Study Description", data.study?.description || "N/A"],
    ["Modality",          data.study?.modality || "N/A"],
    ["Body Part",         data.study?.bodyPart || "N/A"],
    ["Study Date",        data.study?.studyDate ? new Date(data.study.studyDate).toLocaleDateString() : "N/A"],
  ];

  for (let i = 0; i < Math.max(patientFields.length, studyFields.length); i++) {
    ensureSpace(10);
    const pf = patientFields[i];
    const sf = studyFields[i];
    if (pf) {
      doc.setFontSize(8); doc.setTextColor(120);
      doc.text(pf[0].toUpperCase(), marginL, y);
      doc.setFontSize(10); doc.setTextColor(30);
      doc.text(pf[1], marginL, y + 4);
    }
    if (sf) {
      doc.setFontSize(8); doc.setTextColor(120);
      doc.text(sf[0].toUpperCase(), col2X, y);
      doc.setFontSize(10); doc.setTextColor(30);
      doc.text(sf[1], col2X, y + 4);
    }
    y += 10;
  }

  y += 3;
  rule();

  // Report date & radiologist
  ensureSpace(14);
  doc.setFontSize(9); doc.setTextColor(120);
  doc.text("REPORT DATE", marginL, y);
  doc.text("RADIOLOGIST", col2X, y);
  y += 4;
  doc.setFontSize(10); doc.setTextColor(30);
  doc.text(new Date(data.report.createdAt).toLocaleString(), marginL, y);
  doc.text(data.radiologistName || "—", col2X, y);
  y += 9;
  rule();

  // ── Report body ───────────────────────────────────────────────────────────
  section("Findings", data.report.findings);
  section("Impression", data.report.impression);
  if (data.report.recommendations) {
    section("Recommendations", data.report.recommendations);
  }

  // Footer on the last page
  drawFooter();

  const safeName = (data.patient?.name || "report").replace(/\s+/g, "_");
  doc.save(`${safeName}_report_${new Date().toISOString().split("T")[0]}.pdf`);
}
